services:
  client:
    image: ${DOCKERHUB_USERNAME}/dair-client:latest
    pull_policy: always
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    networks:
      - dair-client-network

networks:
  dair-client-network:
    name: dair-client-network
