providers = []

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'

[phases.build]
dependsOn = ['install']
cmds = ['bun run build']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['bun i --no-save']
cacheDirectories = ['/root/.bun']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_22',
    'bun',
]
nixpkgsArchive = 'ed264a8c48d8c2fe55e9d5a9bbb78c23bc07fc0b'

[start]
cmd = 'bun run start'