name: Build Docker images
 
on:
  push:
    branches: 
      - main
      - bh
  workflow_dispatch:
 
jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, client]
        include:
          - service: api
            dockerfile: ./api/Dockerfile
            tag: dair-api:latest
            compose_id_name: DOKPLOY_API_COMPOSE_ID

          - service: client
            dockerfile: ./client/Dockerfile
            tag: dair-client:latest
            compose_id_name: DOKPLOY_CLIENT_COMPOSE_ID
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            CLIENT_URL=${{ vars.CLIENT_URL }}
            API_URL=${{ vars.API_URL }}
            SOCIAL_DISCORD_URL=${{ vars.SOCIAL_DISCORD_URL }}
            SOCIAL_GITHUB_URL=${{ vars.SOCIAL_GITHUB_URL }}
            SOCIAL_TWITTER_URL=${{ vars.SOCIAL_TWITTER_URL }}
            SOCIAL_KOFI_URL=${{ vars.SOCIAL_KOFI_URL }}
            BRAWLHALLA_WIKI_URL=${{ vars.BRAWLHALLA_WIKI_URL }}
            GOOGLE_ANALYTICS_TRACKING_ID=${{ vars.GOOGLE_ANALYTICS_TRACKING_ID }}
            GOOGLE_ADSENSE_ID=${{ vars.GOOGLE_ADSENSE_ID }}
      - name: Trigger Dokploy Deployment
        run: |
            curl -X 'POST' '${{ secrets.DOKPLOY_URL }}/api/trpc/compose.deploy' \
            -d '{
                "json":{
                    "composeId": "${{ secrets[matrix.compose_id_name] }}"
                }
            }' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
            -H 'Content-Type: application/json'
